
name: Publish Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install lib dependencies
      run: cd ./projects/diaas-angular-cdk-hal
    
    # - name: Test library
    #   run: cd ./projects/diaas-angular-cdk-hal && npm run test
    
    # - name: Build angular release cdk site
    #   run: cd . && npm run build-release-cdk-site -- --baseHref=/tools/angular/${{steps.split.outputs._0}}/ --deploy-url /tools/angular/${{steps.split.outputs._0}}/
    #   env: 
    #       TAG_NAME: ${{ github.event.release.tag_name }}

    # - name: Move RELEASE docs to S3
    #   run: node scripts/release-docs.js $TAG_NAME
    #   env:
    #     TAG_NAME: ${{ github.event.release.tag_name }}
